import Image from "next/image";
import React from "react";
import Navbar from "../../components/Navbar";
import Router from "next/router";

export default function User({ data }) {
  console.log(data);
  const handleuserDetail = (id) => {
    Router.push(`users/${id}`);
  };
  return (
    <div>
      <title>Semina ||Page User</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Navbar />
      <h1 className="title">Halaman users</h1>
      <Image src="/tes.png" width={"100"} height={"100"} alt="user" />
      {/* <img src="/tes.png" width={"100"} height={"100"} alt="user" /> */}
      <ul>
        {data.map((item) => {
          return (
            <div key={item.id} onClick={() => handleuserDetail(item.id)}>
              <li>{item.name}</li>
              <li>{item.email}</li>
              =====================
            </div>
          );
        })}
      </ul>
    </div>
  );
}

export async function getServerSideProps(context) {
  // Fetch data from external API
  const res = await fetch(`https://jsonplaceholder.typicode.com/users`);
  const data = await res.json();
  console.log("sdfsdfsdf", data);
  // Pass data to the page via props
  return { props: { data } };
}
