/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Brands from "../components/Brands";
import CardEvent from "../components/CardEvent";
import Footer from "../components/Footer";
import Header from "../components/Header";

import Statistics from "../components/Statistics";
import Stories from "../components/Stories";

import { getData } from "../utils/fetchData";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Brands />
      <CardEvent data={data} title="Featured Event" subTitle="Grow Today" />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData("api/v1/participants/landing-page");
  const res = req.data;

  return {
    props: { data: res },
  };
}
